
# https://help.github.com/articles/using-jekyll-with-pages/
# Github Pages override these options.
safe: true
lsi: false

# Dependencies
markdown:       kramdown
highlighter:    pygments

# kramdown:
# fenced_code_blocks: true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               WinterDay
tagline:             Taesoon Park's blog
description:         Blog
url:                 http://taesoon.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Taesoon Park
  url:               https://twitter.com/spring2me
  email:             taesoon@gmail.com

# Custom vars
version:             1.0.0
